"""empty message

Revision ID: 2992875b2a4f
Revises: 
Create Date: 2018-11-26 00:17:22.148150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2992875b2a4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('template_name', sa.String(length=120), nullable=True),
    sa.Column('template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_owner'), 'template', ['owner'], unique=False)
    op.create_index(op.f('ix_template_template_name'), 'template', ['template_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_template_name'), table_name='template')
    op.drop_index(op.f('ix_template_owner'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
